// Code generated by protoc-gen-go.
// source: university/university.proto
// DO NOT EDIT!

/*
Package university is a generated protocol buffer package.

It is generated from these files:
	university/university.proto

It has these top-level messages:
	Professor
	Course
	Student
	GetEntityInfoRequest
*/
package university

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Gender int32

const (
	Gender_UNKNOWN_GENDER Gender = 0
	Gender_MALE           Gender = 1
	Gender_FEMALE         Gender = 2
)

var Gender_name = map[int32]string{
	0: "UNKNOWN_GENDER",
	1: "MALE",
	2: "FEMALE",
}
var Gender_value = map[string]int32{
	"UNKNOWN_GENDER": 0,
	"MALE":           1,
	"FEMALE":         2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Professor struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Gender Gender `protobuf:"varint,3,opt,name=gender,enum=university.Gender" json:"gender,omitempty"`
	Age    uint32 `protobuf:"varint,4,opt,name=age" json:"age,omitempty"`
}

func (m *Professor) Reset()                    { *m = Professor{} }
func (m *Professor) String() string            { return proto.CompactTextString(m) }
func (*Professor) ProtoMessage()               {}
func (*Professor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Professor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Professor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Professor) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN_GENDER
}

func (m *Professor) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type Course struct {
	Id         string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Professors []*Professor `protobuf:"bytes,3,rep,name=professors" json:"professors,omitempty"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Course) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetProfessors() []*Professor {
	if m != nil {
		return m.Professors
	}
	return nil
}

type Student struct {
	Id              string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gender          Gender    `protobuf:"varint,2,opt,name=gender,enum=university.Gender" json:"gender,omitempty"`
	Name            string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Age             uint32    `protobuf:"varint,4,opt,name=age" json:"age,omitempty"`
	RegistedCourses []*Course `protobuf:"bytes,5,rep,name=registed_courses,json=registedCourses" json:"registed_courses,omitempty"`
}

func (m *Student) Reset()                    { *m = Student{} }
func (m *Student) String() string            { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()               {}
func (*Student) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Student) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Student) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN_GENDER
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetRegistedCourses() []*Course {
	if m != nil {
		return m.RegistedCourses
	}
	return nil
}

type GetEntityInfoRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetEntityInfoRequest) Reset()                    { *m = GetEntityInfoRequest{} }
func (m *GetEntityInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntityInfoRequest) ProtoMessage()               {}
func (*GetEntityInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetEntityInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Professor)(nil), "university.Professor")
	proto.RegisterType((*Course)(nil), "university.Course")
	proto.RegisterType((*Student)(nil), "university.Student")
	proto.RegisterType((*GetEntityInfoRequest)(nil), "university.GetEntityInfoRequest")
	proto.RegisterEnum("university.Gender", Gender_name, Gender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UniversityManager service

type UniversityManagerClient interface {
	GetStudentInfo(ctx context.Context, in *GetEntityInfoRequest, opts ...grpc.CallOption) (*Student, error)
	GetCourseInfo(ctx context.Context, in *GetEntityInfoRequest, opts ...grpc.CallOption) (*Course, error)
	GetProfessorInfo(ctx context.Context, in *GetEntityInfoRequest, opts ...grpc.CallOption) (*Professor, error)
}

type universityManagerClient struct {
	cc *grpc.ClientConn
}

func NewUniversityManagerClient(cc *grpc.ClientConn) UniversityManagerClient {
	return &universityManagerClient{cc}
}

func (c *universityManagerClient) GetStudentInfo(ctx context.Context, in *GetEntityInfoRequest, opts ...grpc.CallOption) (*Student, error) {
	out := new(Student)
	err := grpc.Invoke(ctx, "/university.UniversityManager/GetStudentInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagerClient) GetCourseInfo(ctx context.Context, in *GetEntityInfoRequest, opts ...grpc.CallOption) (*Course, error) {
	out := new(Course)
	err := grpc.Invoke(ctx, "/university.UniversityManager/GetCourseInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagerClient) GetProfessorInfo(ctx context.Context, in *GetEntityInfoRequest, opts ...grpc.CallOption) (*Professor, error) {
	out := new(Professor)
	err := grpc.Invoke(ctx, "/university.UniversityManager/GetProfessorInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UniversityManager service

type UniversityManagerServer interface {
	GetStudentInfo(context.Context, *GetEntityInfoRequest) (*Student, error)
	GetCourseInfo(context.Context, *GetEntityInfoRequest) (*Course, error)
	GetProfessorInfo(context.Context, *GetEntityInfoRequest) (*Professor, error)
}

func RegisterUniversityManagerServer(s *grpc.Server, srv UniversityManagerServer) {
	s.RegisterService(&_UniversityManager_serviceDesc, srv)
}

func _UniversityManager_GetStudentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagerServer).GetStudentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university.UniversityManager/GetStudentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagerServer).GetStudentInfo(ctx, req.(*GetEntityInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManager_GetCourseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagerServer).GetCourseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university.UniversityManager/GetCourseInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagerServer).GetCourseInfo(ctx, req.(*GetEntityInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManager_GetProfessorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagerServer).GetProfessorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university.UniversityManager/GetProfessorInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagerServer).GetProfessorInfo(ctx, req.(*GetEntityInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UniversityManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "university.UniversityManager",
	HandlerType: (*UniversityManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentInfo",
			Handler:    _UniversityManager_GetStudentInfo_Handler,
		},
		{
			MethodName: "GetCourseInfo",
			Handler:    _UniversityManager_GetCourseInfo_Handler,
		},
		{
			MethodName: "GetProfessorInfo",
			Handler:    _UniversityManager_GetProfessorInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "university/university.proto",
}

func init() { proto.RegisterFile("university/university.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x8e, 0x93, 0x50,
	0x14, 0x86, 0x05, 0x2a, 0x3a, 0xc7, 0x0c, 0xc3, 0x1c, 0xc7, 0x48, 0xaa, 0x8b, 0x09, 0x0b, 0x33,
	0x99, 0xc5, 0x10, 0x31, 0x2e, 0x5d, 0x18, 0x45, 0x62, 0xb4, 0x68, 0x30, 0x8d, 0x3b, 0x1b, 0x2c,
	0xb7, 0x84, 0xc4, 0xde, 0x5b, 0xef, 0xbd, 0x34, 0x31, 0xc6, 0x8d, 0xaf, 0xe0, 0x5b, 0xf8, 0x12,
	0x3e, 0x84, 0xaf, 0xe0, 0x83, 0x78, 0xb9, 0x14, 0x4a, 0x43, 0x93, 0xe9, 0xee, 0xf4, 0xf4, 0xef,
	0xf9, 0xbe, 0x73, 0x0a, 0xf0, 0xa0, 0xa2, 0xe5, 0x9a, 0x70, 0x51, 0xca, 0x6f, 0xc1, 0xb6, 0xbc,
	0x5a, 0x71, 0x26, 0x19, 0xc2, 0xb6, 0x33, 0x7e, 0x58, 0x30, 0x56, 0x7c, 0x21, 0x41, 0xb6, 0x2a,
	0x83, 0x8c, 0x52, 0x26, 0x33, 0x59, 0x32, 0x2a, 0x9a, 0xa4, 0xbf, 0x84, 0xa3, 0xf7, 0x9c, 0x2d,
	0x88, 0x10, 0x8c, 0xa3, 0x03, 0x66, 0x99, 0x7b, 0xc6, 0xb9, 0x71, 0x71, 0x94, 0xaa, 0x0a, 0x11,
	0x46, 0x34, 0x5b, 0x12, 0xcf, 0xd4, 0x1d, 0x5d, 0xe3, 0x25, 0xd8, 0x05, 0xa1, 0x39, 0xe1, 0x9e,
	0xa5, 0xba, 0x4e, 0x88, 0x57, 0x3d, 0x7a, 0xac, 0xbf, 0x49, 0x37, 0x09, 0x74, 0xc1, 0xca, 0x0a,
	0xe2, 0x8d, 0x54, 0xf0, 0x38, 0xad, 0x4b, 0x7f, 0x0e, 0xf6, 0x0b, 0x56, 0x71, 0x41, 0x0e, 0x62,
	0x3d, 0x05, 0x58, 0xb5, 0x72, 0x42, 0xf1, 0xac, 0x8b, 0x3b, 0xe1, 0xbd, 0x3e, 0xaf, 0x53, 0x4f,
	0x7b, 0x41, 0xff, 0xb7, 0x01, 0xb7, 0x3e, 0xc8, 0x2a, 0x27, 0x54, 0x0e, 0x30, 0x5b, 0x7d, 0xf3,
	0x5a, 0xfd, 0x56, 0xc9, 0xea, 0x29, 0x0d, 0x56, 0xc2, 0x67, 0xe0, 0x72, 0x52, 0x94, 0x42, 0x92,
	0x7c, 0x36, 0xd7, 0xbb, 0x09, 0xef, 0xa6, 0x56, 0xdd, 0x99, 0xdd, 0xac, 0x9d, 0x9e, 0xb4, 0xd9,
	0xe6, 0xb3, 0xf0, 0x1f, 0xc1, 0x59, 0x4c, 0x64, 0x44, 0xa5, 0x0a, 0xbd, 0xa6, 0x0b, 0x96, 0x92,
	0xaf, 0x15, 0x11, 0x03, 0xf1, 0xcb, 0x10, 0xec, 0xb8, 0xd5, 0x72, 0xa6, 0xc9, 0x9b, 0xe4, 0xdd,
	0xc7, 0x64, 0x16, 0x47, 0xc9, 0xcb, 0x28, 0x75, 0x6f, 0xe0, 0x6d, 0x18, 0x4d, 0x9e, 0xbf, 0x8d,
	0x5c, 0x03, 0x01, 0xec, 0x57, 0x91, 0xae, 0xcd, 0xf0, 0x8f, 0x09, 0xa7, 0xd3, 0x4e, 0x61, 0x92,
	0x51, 0xe5, 0xcb, 0x31, 0x03, 0x47, 0x11, 0x37, 0x07, 0xaa, 0x91, 0x78, 0xbe, 0x7b, 0x84, 0xa1,
	0xcd, 0xf8, 0x6e, 0x3f, 0xb1, 0xf9, 0xa9, 0xef, 0xfd, 0xfc, 0xfb, 0xef, 0x97, 0x89, 0xe8, 0x06,
	0xeb, 0xc7, 0x81, 0x68, 0x9a, 0xc1, 0xf7, 0x32, 0xff, 0x81, 0x9f, 0xe0, 0x58, 0x8d, 0x69, 0x56,
	0x3c, 0x90, 0xb0, 0xe7, 0x58, 0xfe, 0x7d, 0x0d, 0x38, 0xc5, 0x93, 0x1a, 0xd0, 0xdc, 0xb6, 0x99,
	0x5f, 0x80, 0xab, 0x86, 0x74, 0xff, 0xfe, 0x81, 0x88, 0xfd, 0x8f, 0x8e, 0x3f, 0xd6, 0x94, 0x33,
	0xc4, 0x9a, 0xd2, 0x3d, 0x46, 0x1a, 0xf4, 0xd9, 0xd6, 0x6f, 0xc9, 0x93, 0xff, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc3, 0xcb, 0x0f, 0x75, 0x6e, 0x03, 0x00, 0x00,
}
